/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FRAMES;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jlmmj
 */
public class Buscar extends javax.swing.JFrame {
ArrayList<String[]> my_dict = new ArrayList<>();  
DefaultTableModel modelo= new DefaultTableModel();
int init = 1;
    /**
     * Creates new form Buscar
     * @throws java.sql.SQLException
     * @throws java.lang.CloneNotSupportedException
     */
    public Buscar() throws SQLException, CloneNotSupportedException {
        initComponents();
        this.setLocationRelativeTo(this);
        this.getContentPane().setBackground(new Color(204, 255, 255));
        Clases.data.setElements();
        Table("Reset", null);
    }

    public void Table(String tipo, String buscar) throws SQLException, CloneNotSupportedException{
        ArrayList<String> lista = new ArrayList<>();
        
        if(init==1){
            init=0;
            lista.add("ID");
            lista.add("Descripción");
            lista.add("Prioridad");
            lista.add("Proveedor");
            lista.add("Costo");
            lista.add("Razón Social");
        }

        for (String columna : lista) {
            modelo.addColumn(columna);
        }
        TBL_AREA.setModel(modelo);

        if(null != tipo)switch (tipo) {
            case "Reset":{
                modelo.setRowCount(0);//ELIMINA LOS DATOS DE LA TABLA
                my_dict=Clases.data.getElements();//TRAE LOS ELEMENTOS DE LA BASE DE DATOS
                my_dict=Clases.data.setFormatList(my_dict);//A LOS ELEMENTOS DE LA BASE DE DATOS LE DA AL CÓDIGO EL FORMATO
                break;
            }
            case "Busqueda Binaria":{
                int index = Clases.data.Busqueda_binaria(Integer.parseInt(buscar));
                if(index >=0){
                    modelo.setRowCount(0);//ELIMINA LOS DATOS DE LA TABLA
                    my_dict.clear();//ELIMINA EL CONTENIDO DE LA ARRAYLIST
                    my_dict.add(Clases.data.Quick_sort(0).get(index));//LLAMA AL METODO DE ORDENACIÓN Y PIDE UN ELEMENTO ESPECIFICO CON EL INDEX
                    my_dict=Clases.data.setFormatList(my_dict);//LE DA EL FORMATO CORRECTO AL CÓDIGO
                }else{
                    JOptionPane.showMessageDialog(null, "El elemento buscado no se encuentra en la Base de Datos.");
                    modelo.setRowCount(0);//ELIMINA LOS DATOS DE LA TABLA
                    my_dict.clear();//ELIMINA LOS DATOS DE LA ARRAYLIST
                    my_dict=Clases.data.getElements();
                    my_dict=Clases.data.setFormatList(my_dict);
                    CBO_BUSQUEDA.setSelectedIndex(0);
                    TXT_BUSCAR.setText(null);
                }   break;
            }
            case "Busqueda Secuencial":{
                int index = Clases.data.Busqueda_secuencial(Integer.parseInt(buscar));//ENTREGA AL METODO BUSQ SECUENCIAL EL ARRAYLIST SIN LAS LETRAS DE CODIGO Y EL ELEMENTO A BUSCAR
                if(index>=0){
                    modelo.setRowCount(0);//ELIMINA LOS DATOS DE LA TABLA
                    my_dict.clear();//ELIMINA LOS DATOS DE LA ARRAYLIST
                    my_dict.add(Clases.data.Quick_sort(0).get(index));//LLAMA AL METODO DE ORDENACIÓN Y PIDE UN ELEMENTO ESPECIFICO CON EL INDEX
                    my_dict=Clases.data.setFormatList(my_dict);
                }else{
                    JOptionPane.showMessageDialog(null, "El elemento buscado no se encuentra en la Base de Datos.");
                    modelo.setRowCount(0);//ELIMINA LOS DATOS DE LA TABLA
                    my_dict.clear();//ELIMINA LOS DATOS DE LA ARRAYLIST
                    my_dict=Clases.data.getElements();
                    my_dict=Clases.data.setFormatList(my_dict);
                    CBO_BUSQUEDA.setSelectedIndex(0);
                    TXT_BUSCAR.setText(null);
                }   
                break;
            }
            default:
                break;
        }
        
        for (String []Datos : my_dict){
            modelo.addRow(Datos);//AGREGA LAS FILAS AL MODELO
        }
        TBL_AREA.setModel(modelo);//AGREGA EL MODELO A LA TABLA
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTN_BACK = new javax.swing.JButton();
        TXT_BUSCAR = new javax.swing.JTextField();
        BTN_BUSCAR = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBL_AREA = new javax.swing.JTable();
        CBO_BUSQUEDA = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar en Base de Datos");
        setBackground(new java.awt.Color(204, 255, 204));

        BTN_BACK.setBackground(new java.awt.Color(255, 204, 204));
        BTN_BACK.setForeground(new java.awt.Color(0, 0, 0));
        BTN_BACK.setText("Volver");
        BTN_BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BACKActionPerformed(evt);
            }
        });

        TXT_BUSCAR.setBackground(new java.awt.Color(255, 204, 204));
        TXT_BUSCAR.setForeground(new java.awt.Color(0, 0, 0));

        BTN_BUSCAR.setBackground(new java.awt.Color(255, 204, 204));
        BTN_BUSCAR.setForeground(new java.awt.Color(0, 0, 0));
        BTN_BUSCAR.setText("Buscar");
        BTN_BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_BUSCARActionPerformed(evt);
            }
        });

        TBL_AREA.setBackground(new java.awt.Color(102, 204, 255));
        TBL_AREA.setForeground(new java.awt.Color(0, 0, 0));
        TBL_AREA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Zona", "Local", "Sistema", "Descripción", "Prioridad", "Tipo", "Proveedor", "Costo", "Razon Social", "Encargado"
            }
        ));
        jScrollPane2.setViewportView(TBL_AREA);

        CBO_BUSQUEDA.setBackground(new java.awt.Color(255, 204, 204));
        CBO_BUSQUEDA.setForeground(new java.awt.Color(0, 0, 0));
        CBO_BUSQUEDA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Busqueda Binaria", "Busqueda Secuencial" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Método de busqueda:");

        jSeparator1.setBackground(new java.awt.Color(255, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(CBO_BUSQUEDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(TXT_BUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(318, 318, 318)
                                .addComponent(jLabel1)))
                        .addGap(74, 74, 74)
                        .addComponent(BTN_BUSCAR))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BTN_BACK)
                .addGap(388, 388, 388))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXT_BUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_BUSCAR)
                    .addComponent(CBO_BUSQUEDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTN_BACK)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BACKActionPerformed
        Main ma= new Main();
        ma.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_BACKActionPerformed

    private void BTN_BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_BUSCARActionPerformed
        try{
            if(TXT_BUSCAR.getText() == null || TXT_BUSCAR.getText().equals(" ")){
                JOptionPane.showMessageDialog(null, "No puede buscar elementos vacios");
            }else if(CBO_BUSQUEDA.getSelectedItem().equals("Ninguno")){
                /*TableRowSorter<TableModel> fil = new TableRowSorter<>(TBL_AREA.getModel());
                TBL_AREA.setRowSorter(fil);
                fil.setRowFilter(RowFilter.regexFilter(TXT_BUSCAR.getText()));*/
                JOptionPane.showMessageDialog(null, "Debe escoger un método de busqueda.");
            }else if(CBO_BUSQUEDA.getSelectedItem().equals("Busqueda Binaria")){
                try {
                    Table("Busqueda Binaria", TXT_BUSCAR.getText());
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Se ha generado un error con la Base de Datos.");
                } catch (CloneNotSupportedException ex) {
                    Logger.getLogger(Buscar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else if(CBO_BUSQUEDA.getSelectedItem().equals("Busqueda Secuencial")){
                try {
                    Table("Busqueda Secuencial", TXT_BUSCAR.getText());
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Se ha generado un error con la Base de Datos.");
                } catch (CloneNotSupportedException ex) {
                    Logger.getLogger(Buscar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }catch(HeadlessException | NumberFormatException ex ){
            JOptionPane.showMessageDialog(null, "Se generó un problema, intente ingresar datos adecuados.");
        }

    }//GEN-LAST:event_BTN_BUSCARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Buscar().setVisible(true);
            } catch (SQLException | CloneNotSupportedException ex) {
                Logger.getLogger(Buscar.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_BACK;
    private javax.swing.JButton BTN_BUSCAR;
    private javax.swing.JComboBox<String> CBO_BUSQUEDA;
    private javax.swing.JTable TBL_AREA;
    private javax.swing.JTextField TXT_BUSCAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
